### ISSUE TITLE
tag tool crashing at the end of the comment

### ISSUE THREAD

**Issue by roll9898** [ElDewrito/HaloOnlineTagTool#21]
Reading tags...
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'F:\Downloads\FlatGrass R08 Release (ED 0.5.0.2)\Patch\maps\tags.dat'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at HaloOnlineTagTool.Program.Main(String[] args)

**Comment by Shockfire** [comment]
As the error implies, it can't find your tags.dat file. Also, I don't provide support for mod-specific issues here. Ask the creator of Flatgrass (Xe_CREATURE) for help instead.

**Comment by roll9898** [comment]
ok, sorry for the truble.
